### ISSUE TITLE
crash ohf ntfy under grapheneos

### ISSUE THREAD

**Issue by topcaser** [binwiederhier/ntfy-android#69]
> <@topcaser:nope.chat> ```
> type: crash
> osVersion: google/husky/husky:14/UD1A.231105.004/2023112900:user/release-keys
> package: io.heckel.ntfy:32
> process: io.heckel.ntfy
> processUptime: 564 + 308 ms
> installer: dev.imranr.obtainium
> 
> java.lang.RuntimeException: Unable to create service io.heckel.ntfy.service.SubscriberService: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service io.heckel.ntfy/.service.SubscriberService
> 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4681)
> 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2271)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:205)
> 	at android.os.Looper.loop(Looper.java:294)
> 	at android.app.ActivityThread.main(ActivityThread.java:8199)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
> 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
> Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service io.heckel.ntfy/.service.SubscriberService
> 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
> 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
> 	at android.os.Parcel.readParcelableInternal(Parcel.java:4890)
> 	at android.os.Parcel.readParcelable(Parcel.java:4872)
> 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
> 	at android.os.Parcel.createException(Parcel.java:3050)
> 	at android.os.Parcel.readException(Parcel.java:3026)
> 	at android.os.Parcel.readException(Parcel.java:2968)
> 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6776)
> 	at android.app.Service.startForeground(Service.java:775)
> 	at io.heckel.ntfy.service.SubscriberService.onCreate(SubscriberService.kt:101)
> 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4668)
> 	... 11 more
> 
> ```

this is a clear app bug

**Comment by scottwallacesh** [comment]
Works for me on GrapheneOS.

**Comment by binwiederhier** [comment]
I have seen this before. I think this is a race condition at startup. It's hard to reproduce though.
